name: "Scan open ports action"
description: "Scan open tcp ports from hostname"
author: 'Tristan Robert'
branding:
  icon: 'activity'  
  color: 'green'
inputs:
  image:
    description: 'Docker image to run nmap with xsltproc'
    default: 'tristanrobert/nmap-docker'
  outputDir:
    description: 'Folder for scan reports'
    default: 'output'
  outputFile:
    description: 'File name for scan reports'
    default: 'nmapvuln.json'
  raw:
    description: 'Raw or reduced JSON'
    default: false
  arguments:
    description: 'arguments passed to nmap'
    default: '-sT -F -Pn scanme.nmap.org'
runs:
  using: 'node12'
  main: 'dist/index.js'
      
